sudo: false
language: cpp
compiler:
  - gcc
os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7.4
      - g++-7.4


before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7.4" CC="gcc-7.4"; fi
script:
  - cd fake_server
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  - ./lab5_fake_server &
  - cd ../../client/test
  - mkdir build && cd build
  - cmake -DCMAKE_COMPILER=$COMPILER .. && make
  - ./runTests