sudo: false
language: cpp
compiler: gcc
os: - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  -export CXX="g++-4.8"; fi
script:
  - cd fake_server
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && cd .. && make; fi
  - ./lab5_fake_server
